# Generated by Django 4.1.3 on 2022-11-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=50, verbose_name='describe')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=3000, verbose_name='status')),
                ('schedule_at', models.DateTimeField(verbose_name='schedule_at')),
            ],
        ),
    ]
